Document: moksha-debug
Title: Debian moksha-debug Manual
Author: <insert document author here>
Abstract: This manual describes what moksha-debug is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/moksha-debug/moksha-debug.sgml.gz

Format: postscript
Files: /usr/share/doc/moksha-debug/moksha-debug.ps.gz

Format: text
Files: /usr/share/doc/moksha-debug/moksha-debug.text.gz

Format: HTML
Index: /usr/share/doc/moksha-debug/html/index.html
Files: /usr/share/doc/moksha-debug/html/*.html
